name: seobi_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  path: ^1.9.0
  uuid: ^4.3.3
  flutter_svg: ^2.0.10
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite_common_ffi: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.svg
    - .env
