name: seobi_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  workmanager: ^0.6.0
  sqflite_common_ffi: ^2.3.2
  path: ^1.9.0
  uuid: ^4.3.3
  flutter_svg: ^2.0.10
  google_sign_in: ^6.3.0
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.2.1
  http: ^1.4.0
  provider: ^6.1.5
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  flutter_keyboard_visibility: ^6.0.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  event_bus: ^2.0.0
  flutter_markdown: ^0.7.7+1
  logger: ^2.4.0
  flutter_dash: ^1.0.0
  url_launcher: ^6.2.5
  geolocator: ^14.0.1
  screen_corner_radius: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.svg
    - .env
